#!/bin/bash

function PrintHelp {
    echo "audiobooks ACTION [ACTION PARAMETERS]"
    echo
    echo Actions:
    echo "  -t, --trim              [audiobook.m4b] [Length]        Trim the [audiobook.m4b] to [Length] (HH:MM:SS.000). This will copy to a new file as some meta data will be lost."
    echo "  -m, --merge                                             Merge all files in this folder into a single file with the same name as the folder."

    echo "  -c, --chapters                                          Process audiobook chapters - use 'audiobooks -c -h' for details."
}

function Trim {
    audiobook="$1"
    length="$2"

    backupFile=$(sed "s/\.m4b$/_bck.m4b/" <<< "$audiobook")

    echo "Trimming file: \"$audiobook\""
    mv "$audiobook" "$backupFile"

    ffmpeg -i "$backupFile" -vn -acodec copy -t $length -f mp4 "$audiobook"
}

function Merge {
    outputFile=$(pwd | sed 's|.*/\(.*\)|\1|').m4b
    outputFileTemp=$(sed "s/\.m4b$/_out.m4b/" <<< "$outputFile")

    echo "Merging files to audiobook: \"$outputFile\""
    m4b-tool merge ./. --output-file "$outputFileTemp" --no-conversion -v

    #I've been seeing some very odd timing issues, particularly when merging mp3 files. Setting format to mp4 seems to fix them.
    ffmpeg -i "$outputFileTemp" -vn -acodec copy -f mp4 "$outputFile"
    rm "$outputFileTemp"
}

folder=$(dirname "$0")

case "$1" in
    -t|--trim) shift; Trim "$@" ;;
    -m|--merge) shift; Merge "$@" ;;
    -c| --chapters) shift; "$folder/chapters" "$@" ;;
    -h|--help) PrintHelp ;;
    *) echo "Unknown action: '$1'"
esac